name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # 또는 master, 배포 브랜치명

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker hub 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: minicom365/git-sveltekit-runner:latest
